1.A Robot moves in a Plane starting from the origin point (0,0). The robot can move toward UP, DOWN, LEFT, RIGHT. The trace of Robot movement is as given following:UP 5DOWN 3LEFT 3RIGHT 2The numbers after directions are steps.  Write a program to compute the distance current position after sequence of movements.Hint: Use math module.

In [49]:
global point
point =[0,0]

In [46]:
def move(St,val):
    s=str.lower(St)
    if s=='up':
        point[1]=point[1]+val
        print(point)
    elif s=='down':
        point[1]=point[1]-val
        print(point)
    elif s=='left':
        point[0]=point[0]-val
        print(point)
    elif s=='right':
        point[0]=point[0]+val
        print(point)

In [50]:
print('Enter commands , press x to escape')
while 1:
    cmd=input('Enter commands: ')
    if (cmd =='x'):
        break;
    s=str.split(cmd)
    move(s[0],int(s[1]))


Enter commands , press x to escape
Enter commands: up 5
[0, 5]
Enter commands: down 3
[0, 2]
Enter commands: left 3
[-3, 2]
Enter commands: right 2
[-1, 2]
Enter commands: x


In [51]:
import math
dist = math.sqrt(point[0]**2+point[1]**2) # formula m=√x2+y2
print(dist)

2.23606797749979


2.Data of XYZ company is stored in sorted list. Write a program for searching specific data from that list.Hint: Use if/elif to deal with conditions.

In [63]:
lst1=['h','a','z','k','a']
lst1=sorted(lst1)
print('sorted list :',lst1)
data=input('Enter the data to search')

x=[i for i,j in enumerate(lst1) if j==data]
print('found at index:',x)


sorted list : ['a', 'a', 'h', 'k', 'z']
Enter the data to searcha
found at index: [0, 1]


3.Weather forecasting organization wants to show is it day or night. So, write a program for such organization to findwhether is it dark outside or not.Hint: Use time module

In [80]:
from datetime import datetime

now = datetime.now()

current_time = now.strftime("%H:%M:%S")
print("Current Time =", current_time)

Current Time = 15:13:30


In [92]:
int(current_time.split(':')[0])<18 and int(current_time.split(':')[0])>5 #assuming it sunset at 6pm and sunrise at 5am

True

4.Write a program to find distancebetween two locations when their latitude and longitudes are given.Hint: Use math module.

In [93]:
from math import radians, sin, cos, acos

print("Input coordinates of two points:")
slat = radians(float(input("Starting latitude: ")))
slon = radians(float(input("Ending longitude: ")))
elat = radians(float(input("Starting latitude: ")))
elon = radians(float(input("Ending longitude: ")))

dist = 6371.01 * acos(sin(slat)*sin(elat) + cos(slat)*cos(elat)*cos(slon - elon))
print("The distance is %.2fkm." % dist)

Input coordinates of two points:
Starting latitude: 10
Ending longitude: 20
Starting latitude: 30
Ending longitude: 40
The distance is 3040.61km.


5.Design a software for bank system. There should be options like cash withdraw, cash credit and change password. According to user input, the software should provide required output.Hint: Use if else statements and functions

In [96]:
class Bank_Account:
    def __init__(self,indeposit):
        self.balance=indeposit
    def check_balance(self):
        print("remaining balance is ",self.balance)
    def deposit(self,amount):
        self.balance+=amount
        print(amount," money is deposited")
    def withdraw(self,amount):
        if(self.balance-amount>=0):
            self.balance-=amount;
            print(amount,"is withdrawn")
        else:
            print("cannot withdraw amount, insufficient balance")

In [97]:
obj1=Bank_Account(500)
obj1.check_balance()

remaining balance is  500


6.Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line.

In [99]:
x= [i for i in range(2000,3201) if i%7==0 and i%5!=0]
print(x)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


7.Write a program which can compute the factorial of a given numbers. Use recursion to find it. Hint: Suppose the following input is supplied to the program:8Then, the output should be:40320

In [109]:
def factorial(n):
    if(n==0):
        return 1;
    return n*factorial(n-1);

In [111]:
factorial(8)

40320

8.Write a program that calculates and prints the value according to the given formula:Q = Square root of [(2 * C * D)/H]Following are the fixed values of C and H: C is 50. H is 30.D  is  the  variable  whose  values  should  be  input  to  your  program  in  a  comma-separated sequence. Example:Let  us  assume  the  following  comma  separated  input  sequence  is  given  to  the program:100,150,180The output of the program should be:18,22,24

In [133]:
#100,150,180
def gen_num(*args):
    for i in args:
        x= round(math.sqrt((2*50*i)/30))
        print(x,end=',')


In [134]:
gen_num(100,150,180)

18,22,24,

9.Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.Note: i=0,1.., X-1; j=0,1,¡-Y-1.Example:Suppose the following inputs are given to the program:3,5Then, the output of the program should be:[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 

In [142]:
import numpy as np

In [182]:
def genList(a,b):
    lst =[]
    for i in range(a):
        lst.append([x*i for x in range(b)])
    
    return lst   

In [183]:
a=np.array(genList(3,5))
print(a)

[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


10.Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically. Suppose the following input is supplied to the program:without,hello,bag,worldThen, the output should be:bag,hello,without,world

In [188]:
words = input('Enter input')

Enter inputwithout,hello,bag,world


In [199]:
l=str.split(words,',')
st=sorted(l)

In [209]:
type(str(st))
s=str(st)

In [222]:
k=s.replace('[','').replace(']','').replace(' ','')
print(k)

'bag','hello','without','world'


11.Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized. Suppose the following inputis supplied to the program:Hello worldPractice makes perfectThen, the output should be:HELLO WORLDPRACTICE MAKES PERFECT

In [242]:
def getSeq(option=1):
    lst=[]
    print('Enter exit to escape')
    while 1:
        w=input('Enter the word')
        if(w == 'exit'):
            return lst
        if(option ==1):    
            lst.append(str.upper(w))
        else:
            lst.append(w)

In [244]:
l=getSeq()
for i in l:
    print(str(i))

Enter exit to escape
Enter the wordhello world
Enter the wordpractise makes perfect
Enter the wordexit
HELLO WORLD
PRACTISE MAKES PERFECT


12.Write a program that accepts a sequence of whitespace separated words as input and   prints   the   words   after   removing   all   duplicate   words   and   sorting   them alphanumerically. Suppose the following input is supplied to the program:hello world and practice makes perfect and hello world againThen, the output should be:again and hello makes perfect practice world

In [253]:
words=input('Enter words')
l2=str.split(words)

Enter wordshello world and practice makes perfect and hello world again


In [254]:
l2=sorted(l2)


In [268]:
l3= [l2[i] for i in range(len(l2)-1) if l2[i]!=l2[i+1]]

In [269]:
l3

['again', 'and', 'hello', 'makes', 'perfect', 'practice']

In [273]:
for i in l3:
    print(str(i),end=' ')

again and hello makes perfect practice 

13.Write  a  program  which  accepts  a  sequence  of  comma  separated  4  digit  binary numbers  as  its  input  and  then  check  whether  they  are  divisible  by  5  or  not.  The numbers that are divisible by 5 are to be printed in a comma separated sequence.

Example:0100,0011,1010,1001Then the output should be:1010


In [282]:
w=input()

0100,0011,1010,1001


In [287]:
k=str.split(w,',')
for i in k:
    if int(i,2)%5==0:
        print(i,end='')

1010

14.Write  a  program  that  accepts  a  sentence  and  calculate  the  number  of  upper  case letters and lower case letters.Suppose the following input is supplied to the program:Hello world!Then, the output should be:UPPER CASE 1LOWER CASE 9

In [293]:
s='Hello world!'
u=0
l=0
for x in s:
    if(x.isupper()):
        u+=1
    elif(x.islower()):
        l+=1

print('UPPER CASE %dLOWER CASE %d'%(u,l))        

UPPER CASE 1LOWER CASE 9


15.Give example of fsum and sum function of math library.

In [295]:
import math

In [305]:
print(sum([10.23,20]))

30.23


In [303]:
math.fsum([10.23,20.22777777777777777])

30.45777777777778